services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/app
  nginx:
    image: nginx:latest
    container_name: cs-lab-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
