FROM node:18-alpine AS base

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "aarch64" ]; then \
      # Optional: check for musl vs gnu
      if ldd --version 2>&1 | grep -qi musl; then \
        npm install @next/swc-linux-arm64-musl; \
      else \
        npm install @next/swc-linux-arm64-gnu; \
      fi; \
    elif [ "$ARCH" = "x86_64" ]; then \
      npm install @next/swc-linux-x64; \
    else \
      echo "Unsupported architecture: $ARCH" && exit 1; \
    fi

# Install dependencies based on the preferred package manager
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

RUN npm i lightningcss-linux-arm64-musl

CMD ["pnpm", "dev"]
